# Generated by Django 5.0.6 on 2024-09-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_storymodel'),
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.createpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='userAccount.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='reactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('👍', '👍'), ('😢', '😢'), ('😆', '😆')], max_length=25)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.createpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reacted_parson', to='userAccount.useraccount')),
            ],
        ),
    ]
