# Generated by Django 5.0.6 on 2024-10-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_commentmodel_reactionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./files/images'),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='./files/videos'),
        ),
    ]
