# Generated by Django 5.0.6 on 2024-10-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_createpost_image_alter_createpost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
